### ISSUE TITLE
runtime error: index out of range in version 1.0

### ISSUE THREAD

**Issue by WilliamDenniss** [bitrise-steplib/steps-generate-shared-scheme#7]
Our build broke with the following error when upgrading from 0.9.5 to 1.0.
https://www.bitrise.io/build/ad3be624b5c878f7

```
+------------------------------------------------------------------------------+
| (3) recreate-user-schemes                                                    |
+------------------------------------------------------------------------------+
| id: recreate-user-schemes                                                    |
| version: 1.0.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2017-05-18T18:29:47-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[18:29:47]  * [OK] Step dependency (go) installed, available. 
Configs:
- ProjectPath: ./Examples/Example-iOS_ObjC/Example-iOS_ObjC.xcworkspace

Searching for workspace shared schemes...
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/bitrise-steplib/steps-recreate-user-schemes/vendor/github.com/bitrise-tools/go-xcode/xcodeproj.WorkspaceSharedSchemes(0xc42001a0fd, 0x38, 0x0, 0x0, 0x0, 0x0, 0xc420072c60)
	/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise-go-toolkit089499755/src/github.com/bitrise-steplib/steps-recreate-user-schemes/vendor/github.com/bitrise-tools/go-xcode/xcodeproj/xcscheme.go:239 +0x252
main.main()
	/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise-go-toolkit089499755/src/github.com/bitrise-steplib/steps-recreate-user-schemes/main.go:59 +0x1e6
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | recreate-user-schemes (exit code: 2)                          | 4.16 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...hub.com/bitrise-steplib/steps-recreate-user-schemes/issues |
| Source: https://github.com/bitrise-steplib/steps-recreate-user-schemes       |
+---+---------------------------------------------------------------+----------+
```

**Comment by viktorbenei** [comment]
Thanks for reporting @WilliamDenniss !

We'll fix this ASAP, in the meantime please use the previous version of the step.

**Comment by trapacska** [comment]
Hey @WilliamDenniss !

Thanks for reporting the issue! The new version ([1.0.1](https://github.com/bitrise-steplib/steps-recreate-user-schemes/releases/tag/1.0.1)) is just released, and the issue is fixed. 🚀🎉

Feel free to re-open the issue if you encounter any issue again!
